title: SciWIn
description: A Concept for a FAIR Scientific Workflow Infrastructure
remote_theme: pages-themes/cayman@v0.2.0
github:
  is_project_page: false
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one